url_primary: slim.dev.samsondoors.co.uk
url_product: products.samsondoors.co.uk
log_path: /opt/lampp/logs/
log_flag_mail: true
log_flag_php: true
mailPort: 1025
#mailAuth: sendmail
debug: true
google_id: FT-FAKE-DEV
prd_google_id: UA-6269913-4
